site_name: Evantis Toolheads
site_description: Documentation for the Evantis Toolheads designed for Mercury One mod.
site_author: Sir_Wash
site_url: https://sir-wash.github.io/Evantis_Toolheads/
repo_url: https://github.com/Sir-Wash/Evantis_Toolheads
repo_name: "GitHub: Sir-Wash/Evantis_Toolheads"
edit_uri: ""
copyright: Copyright &copy; 2023 Sir_Wash

markdown_extensions:
  - admonition
  - attr_list
  - abbr
  - def_list
  - md_in_html
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets:
      auto_append: 
        - include/links.md
        - include/bom_links.md
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer
    - navigation.expand
    - navigation.top
    - toc.integrate
    - toc.follow

  icon:
    logo: material/printer-3d-nozzle
  font:
    text: Noto Sans
  palette: 
    - scheme: slate
      primary: green
      accent: deep orange
      toggle:
        icon: material/lightbulb-off-outline
        name: Switch to light mode
    - scheme: default
      primary: green
      accent: deep orange
      toggle:
        icon: material/lightbulb-on
        name: Switch to dark mode

extra:
  social:
    - icon: simple/kofi
      link: https://ko-fi.com/sir_wash
      name: "Support the Evantis Toolheads using Ko-Fi!"

extra_css:
  - assets/stylesheets/extra.css

plugins:
  - search
      
nav:
  - index.md
  - Guide:
    - compat/index.md
    - tour.md
    - compat/hotends.md
    - compat/drives.md
  - Module Reference:
    - modules/index.md
    - Core Modules:
      - modules/front.md
      - modules/top.md
      - modules/bottom.md
      - modules/rear.md
    - Hotends & Extruders:
      - modules/hotend.md
      - modules/drive.md
    - Other Modules:
      - modules/abl.md
      - modules/stop_block.md
      - modules/pcb_mounts.md
      - modules/other.md
  - Assembly:
    - assembly/index.md
    - assembly/first.md
    - assembly/core.md
    - assembly/fan.md
    - assembly/belts.md
    - assembly/hotend.md
    - assembly/drive.md
    - assembly/abl.md
    - assembly/final.md
  - changelog.md